version: '2'
services:
    mybanking-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/mybanking/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=mybanking
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
